Repository dsstevens/Mixtape, pull requests merged in 2024-01, with the labels that each got.

#27 Feature/main page
  src/components/AlbumDetail/AlbumDetail.tsx
  src/components/AlbumsByYear/AlbumsByYear.tsx
  src/components/App/App.css
  src/components/Dropdown/Dropdown.css
  src/components/Dropdown/Dropdown.tsx
  src/components/Home/Home.css
  src/components/Home/Home.tsx
  src/components/Tracklist/Tracklist.css
  src/components/Tracklist/Tracklist.ts
  src/components/Tracklist/Tracklist.tsx
  src/index.css
Labels: user story

#32 feat: Setup fetch call to grab all albums in our collection
  .env
  .gitignore
  package-lock.json
  package.json
  src/apiCalls.ts
  src/components/Home/Home.tsx
  src/index.js
  tsconfig.json
Labels: task

#30 Feature/single year page
  package-lock.json
  src/components/AlbumsByYear/AlbumsByYear.css
  src/components/AlbumsByYear/AlbumsByYear.tsx
  src/components/Home/Home.tsx
Labels: user story

#36 fix: Remove dotenv require on index.js
  package-lock.json
  src/index.js
Labels: bug

#39 Feature/Header and HomeButton components
  public/index.html
  src/components/AlbumsByYear/AlbumsByYear.css
  src/components/AlbumsByYear/AlbumsByYear.tsx
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Header/Header.css
  src/components/Header/Header.tsx
  src/components/Home/Home.tsx
  src/components/HomeButton/HomeButton.css
  src/components/HomeButton/HomeButton.tsx
Labels: task

#44 Feature/display albums
  public/index.html
  src/apiCalls.ts
  src/components/AlbumsByYear/AlbumsByYear.css
  src/components/AlbumsByYear/AlbumsByYear.tsx
  src/components/Dropdown/Dropdown.css
  src/components/Header/Header.css
  src/components/Header/Header.tsx
  src/components/Home/Home.css
  src/components/HomeButton/HomeButton.css
Labels: task

#46 Feature/album detail page
  public/index.html
  src/apiCalls.ts
  src/components/AlbumDetail/AlbumDetail.css
  src/components/AlbumDetail/AlbumDetail.tsx
  src/components/AlbumsByYear/AlbumsByYear.tsx
  src/components/App/App.tsx
  src/components/Home/Home.tsx
Labels: user story

#47 API cypress testing
  README.md
  cypress.config.ts
  cypress/e2e/spec.cy.ts
  cypress/fixtures/mock-data.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
Labels: test
